name: Install Poetry
description: Install Poetry for managing Python projects
author: Ryan Wersal
inputs:
  poetry-version:
    description: Version of Poetry to install
    required: true
  create-virtualenv:
    description: Create a virtualenv
    default: "true"
    required: false
  virtualenv-in-project:
    description: Create virtualenv within the project
    default: "true"
    required: false
runs:
  using: node12
  main: dist/index.js
