name: Install Poetry
description: Install Poetry for managing Python projects
author: Ryan Wersal
inputs:
  version:
    description: Version of Poetry to install
    default: latest
    required: true
runs:
  using: node12
  main: dist/index.js
