name: Validate

on:
  push:
    branches:
      - releases/*

jobs:
  validate:
    name: Validate ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate
        uses: ./

      - name: Confirm Poetry Works
        run: poetry --help
