name: Validate

on:
  push:
    branches:
      - releases/*

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Validate
      uses: ./
